export const IPC_CHANNELS = {
  cursorPosition: 'psyduck:cursor-position',
  getCursorPosition: 'psyduck:get-cursor-position',
  moveWindow: 'psyduck:move-window',
  setCompanionContentHeight: 'psyduck:set-content-height',
  showCompanionContextMenu: 'psyduck:show-context-menu',
  getRuntimeSettings: 'runtime-settings:get',
  updateUserName: 'runtime-settings:update-user-name',
  runtimeSettingsChanged: 'runtime-settings:changed',
  userNamePanelRequested: 'personal-assistant:user-name-requested',
  reminderCreationPanelRequested:
    'reminders:creation-panel-requested',
  getPreferencesSettings: 'preferences-settings:get',
  updatePreferencesSettings: 'preferences-settings:update',
  updateAiConfiguration: 'preferences-ai:configure',
  askAI: 'ai:ask',
  listAIModels: 'ai:list-models',
  testAIConnection: 'ai:test-connection',
  startPomodoro: 'pomodoro:start',
  customPomodoroPanelClosed: 'pomodoro:custom-panel-closed',
  customPomodoroDurationRequested:
    'pomodoro:custom-duration-requested',
  pomodoroStateChanged: 'pomodoro:state-changed',
  pomodoroCompleted: 'pomodoro:completed',
  createReminder: 'reminders:create',
  updateReminder: 'reminders:update',
  deleteReminder: 'reminders:delete',
  getReminder: 'reminders:get',
  listReminders: 'reminders:list',
  markReminderCompleted: 'reminders:mark-completed',
} as const;
